#ifndef COMMON_H
#define COMMON_H

typedef enum HL_RESULT_ENUM
{
    HL_RESULT_OK,
    HL_RESULT_INVALID_ARG,
    HL_RESULT_EOF,
    HL_RESULT_NOT_FOUND,
    HL_RESULT_ERROR,
    HL_RESULT_BUFFER_OVERFLOW
} HL_RESULT;

#endif // COMMON_H